### ISSUE TITLE
Remaining TODO list to declare the site "migrated"

### ISSUE THREAD

**Issue by mercmobily** [mercmobily/freesoftwaremagazine#1]
We have migrated the site, from Drupal (which comes with a remarkable amount of work in terms of security patching, upkeeping, etc.) to a dynamically generated static file. We are using [Ryver](https://github.com/mercmobily/ryver)  (**NO we are not, 10 years later, we are using Jackyll**) for the site generation and Polymer for the basic widgets.

Here is the last TODO for the web site:
- [x] Make sure Author, short link are clickable (zindex problem, already fixed for section)
- [x] Write README in GitHub, explaining how to clone this repo and make the site
- [x] Tidy up code, adding common functions to info from FSM module 
- [x] Add facebook comments
- [x] Add social sharing buttons
- [x] Make menu on the left look better
- [x] Improve artilceInfo.ejs, make it look more like articleCard, no square brackets
- [x] Check colours and add logo
- [x] Fix link at the top in http://freesoftwaremagazine.com/articles/making_movies_free_software/
- [x] Generally check every internal link (to freesoftwaremagazine.com)
- [x] Make sure that no inner link is using the old (ancient!) /issues/issue_01 format
- [x] Add headings to sections
- [x] Add links to books 
- [x] Fix problem with broken image showing in articles without main image, add a default one
- [x] Make images in articles look better, add missing captions (are they actually missing?)
- [x] Make authors and issues and books page look better thanks to a a nicer heading
- [x] Try to make menus "selected" if possible at the top
- [x] Check that ALL tables are rendered properly in articles, with caption

Later:
- [x] Add analytics
- [ ] Add Adsense back to the magazine
- [ ] Go through the list of links on Webmaster Tools, check that each one works

**Comment by mercmobily** [comment]
Well this is done. I am waiting for the OK from Adsense, and for the initial data from Google Search Tool (it hasn't been called Webmaster tools for years...) but the rest is done.
